--- #YAML:1.0
name:               WebService-Google-Language
version:            0.13
abstract:           Perl interface to the Google AJAX Language API
author:
    - Henning Manske <hma@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  6.17
build_requires:
    HTTP::Response:  0
    JSON:            2.0
    LWP::UserAgent:  0
    Test::More:      0.62
requires:
    JSON:            2.0
    LWP::UserAgent:  0
    perl:            5.006
    URI:             0
resources:
    bugtracker:  http://rt.cpan.org/Public/Dist/Display.html?Name=WebService-Google-Language
    homepage:    http://search.cpan.org/dist/WebService-Google-Language/
    license:     http://dev.perl.org/licenses/
    repository:  https://github.com/hma/WebService-Google-Language
no_index:
    directory:
        - t
        - inc
        - xt
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
